apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: rick
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
    - name: redis-bolt
      port: 6371
      targetPort: 6371