spring:
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: jdbc:postgresql://localhost:5432/rickmorty
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
#  h2:
#    console:
#      enabled: true  # Ativa o console web do H2
#      path: /h2-console  # Define o caminho para acessar o console (http://localhost:8080/h2-console)
  jpa:
    hibernate:
      ddl-auto: none   # usa o schema já criado no container (não recria)
    show-sql: true         # loga queries no console
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Sao_Paulo
  sql:
    init:
      mode: never