spring:
  main:
    allow-bean-definition-overriding: true
  cache:
    type: redis
  data:
    redis:
      host: 10.109.20.118
      port: 6379
      timeout: 2s
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: jdbc:postgresql://10.104.184.52:5432/rickmorty
    #url: jdbc:postgresql://localhost:5432/rickmorty
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none   # usa o schema já criado no container (não recria)
    show-sql: true         # loga queries no console
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Sao_Paulo
  sql:
    init:
      mode: never