apiVersion: v1
kind: Service
metadata:
  namespace: rick
  name: app-svc
spec:
  type: NodePort
  selector:
    app: rick-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30002