apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rick
  name: postgres-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres-deploy
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          imagePullPolicy: Always
          image: leogloriainfnet/rickmorty-db:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_SENHA_NOVA
              value: "123456"
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 5


